import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { ThemeProvider } from "@/components/theme-provider";
import Header from "@/components/Header";
import FirebaseErrorProvider from "@/context/firebaseErrorContext";
import { FirebaseContentProvider } from "@/context/firebaseContentContext";
import Footer from "@/components/Footer";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased bg-background dark:bg-[#202020] flex flex-col min-h-screen`}
      >
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          <FirebaseErrorProvider>
            <FirebaseContentProvider>
              <Header />
              <main className="flex-1 p-4">
                {children}
              </main>
              <Footer />
            </FirebaseContentProvider>
          </FirebaseErrorProvider>
        </ThemeProvider>
      </body>
    </html >
  );
}
